keys:
  - &sh4dow_gpg 57B947A6375A93BFE0489ACFC71894C085934296
  - &novacustom age17aqufzqevnx0n6svpq7w9e4drgck9ewnfawr6rcglkzzsyxq2djqu958zj
  - &dell_latitude age1z579jwaf5pcggnlqrh3zwg8d9mh8kyv7a3gxqnc2vlsnp0rq93nsevz253
creation_rules:
  - path_regex: ^secrets/hosts/novacustom/novacustom\.yaml$
    key_groups:
      - pgp:
          - *sh4dow_gpg
        age:
          - *novacustom
  - path_regex: ^secrets/hosts/dell-latitude/dell-latitude\.yaml$
    key_groups:
      - pgp:
          - *sh4dow_gpg
        age:
          - *dell_latitude
  - path_regex: ^secrets/users/[^/]+\.yaml$
    pgp:
      - *sh4dow_gpg
